spring:

  # DB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA
  jpa:
    hibernate:
      ddl-auto: none

  # JWT
  jwt:
    secret: ${JWT_SECRET_KEY}